networks:
  app-network:

services:
  mysqldb:
    image: mysql
    container_name: mysqldb_fileserver_container
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: cattac
      MYSQL_DATABASE: file_transfer
      MYSQL_USER: root
      MYSQL_PASSWORD: cattac
    ports:
      - "3307:3306"
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql



  web:
    build:
      context: ./WebUI  # 当前目录为上下文，Dockerfile 位于此
    container_name: php_web_container
    ports:
      - "8888:80"  # 将主机的8080端口映射到容器的80端口
    volumes:
      - ./WebUI:/var/www/html  # 将当前目录挂载到容器的 /var/www/html，以便文件实时更新
  
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: python_server_container
    ports:
      - "12345:12345"  # 主机端口5000映射到容器5000端口
    volumes:
      - .:/app  # 挂载根目录到容器中的 /app，以便文件更新
    depends_on:
      - web  # 如果需要先启动 web 服务
